# Generated by Django 5.2.3 on 2025-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaceworld',
            name='is_updates',
            field=models.BooleanField(default=False),
        ),
    ]
