# Generated by Django 5.2.3 on 2025-07-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_peaceworld_is_updated_peaceworld_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peaceworld',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
