# Generated by Django 5.2.3 on 2025-07-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_peaceworld_is_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peaceworld',
            old_name='is_updates',
            new_name='is_updated',
        ),
    ]
