# Generated by Django 5.2.3 on 2025-07-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_peaceworld_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peaceworld',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
