# Generated by Django 5.2.3 on 2025-07-14 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_is_updates_peaceworld_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaceworld',
            name='secret_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
